### PR TITLE
Not required for `tabs` permission

### PR DESCRIPTION
**Pull request by yfdyh000**
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#API_permissions

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
Have you tested this? I trust the docs for Mozilla, but I build for Opera too.

**Comment by yfdyh000** [comment]
I encountered errors with gulp#4.0, so skipped the test.
But I just try modify the dist from AMO and tested, it looks work.

I did not modified the `manifest.opera.json` because there is no evidence from Chrome docs.

**Comment by DaAwesomeP** [comment]
Found it: https://developer.chrome.com/extensions/tabs. Would you mind editing the other file too?

**Comment by DaAwesomeP** [comment]
Thanks!

**Pull request merged**
